name: Integration CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{matrix.node_version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node_version}}
      - name: "Installing dependencies"
        run: npm install
      - name: "Running test cases"
        run: npm run test
